site_name: Awesome Citizen Science Projects
site_description: A curated list of awesome Citizen Science projects
site_author: ODISSEI SoDa Team
repo_name: sodascience/awesome-citizen-science-projects
repo_url: https://github.com/sodascience/awesome-citizen-science-projects
theme:
  name: material
  palette:
    primary: indigo
    accent: teal
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sodascience/awesome-citizen-science-projects
