site_name: Awesome Citizen Science Projects
site_description: A curated list of awesome Citizen Science projects
site_author: SoDa Science
repo_name: sodascience/awesome-citizen-science-projects
repo_url: https://github.com/sodascience/awesome-citizen-science-projectss
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sodascience/awesome-citizen-science-projects
